---
- hosts: 172.31.45.33
  become: yes 
  tasks:
   - include_tasks: myfile.yml


   - name: To create a folder
     file: 
       path: /home/ubuntu/mytestfolder
       state: directory
  
   - name: To copy the file from master to node side
     copy:
       src: mysorce.txt
       dest: /home/ubuntu/mycopyfile

   - name: I want to install apache2
     apt:
       name: apache2
       state: present