---
- hosts: 172.31.45.33
  become: yes 
  tasks:
   - include_tasks: myfile.yml


   - name: To create a folder
     file: 
       path: /home/ubuntu/mytestfolder
       state: directory
  
   - name: To copy the file from master to node side
     copy:
       src: mysorce.txt
       dest: /home/ubuntu/mycopyfile

   - name: I want to install apache2 on nodes
     apt:
       name: apache2
       state: present
    
   - name: dowload the remote file from Internet
     get_url:
      url: https://maha22aug22.s3.us-east-2.amazonaws.com/mahaLogin.war
      dest: /home/ubuntu/shilpalogin.war
      force_basic_auth: yes
  
   - name: I want to copy dynamic files into node side
     template:
      src: myindex.j2
      dest: /var/www/html/index.html