---
- hosts: all
  become: yes
  tasks:
  - name: I want to install apache2 webserver on unbuntu ansible node
    apt:
      name: apache2
      state: present
  - name: I want to start apache2 webserver
    service:
     name: apache2
     state: started